## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 3;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

%global         desktop_id org.gnome.SimpleScan

Name:           simple-scan
Version:        50.0
Release:        %autorelease
Summary:        Simple scanning utility
# Sources are under GPLv3+, icon and help are under CC-BY-SA.
License:        GPL-3.0-or-later AND CC-BY-SA-3.0
URL:            https://gitlab.gnome.org/GNOME/simple-scan
Source0:        https://download.gnome.org/sources/%{name}/%{gnome_major_version}/%{name}-%{version}.tar.xz

BuildRequires:  desktop-file-utils
BuildRequires:  gettext
BuildRequires:  itstool
BuildRequires:  libappstream-glib
BuildRequires:  meson >= 0.46
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(colord)
BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(glib-2.0) >= 2.76
BuildRequires:  pkgconfig(gmodule-export-2.0)
BuildRequires:  pkgconfig(gthread-2.0)
BuildRequires:  pkgconfig(gtk4) >= 4.15.2
BuildRequires:  pkgconfig(gusb) >= 0.2.7
BuildRequires:  pkgconfig(libadwaita-1) >= 1.8.0
BuildRequires:  pkgconfig(libwebp)
BuildRequires:  pkgconfig(libwebpmux)
BuildRequires:  pkgconfig(sane-backends)
BuildRequires:  pkgconfig(zlib)

%if ! 0%{?flatpak}
BuildRequires:  pkgconfig(packagekit-glib2) >= 1.1.5
%endif

Requires:       xdg-utils

%description
Simple Scan is an easy-to-use application, designed to let users connect their
scanner and quickly have the image/document in an appropriate format.

%prep
%autosetup -p1

%build
%meson
%meson_build

%install
%meson_install
%find_lang %{name} --with-man --with-gnome

%check
appstream-util validate-relax --nonet %{buildroot}/%{_metainfodir}/%{desktop_id}.metainfo.xml
desktop-file-validate %{buildroot}/%{_datadir}/applications/%{desktop_id}.desktop

%files -f %{name}.lang
%doc NEWS README.md
%license COPYING
%{_bindir}/%{name}
%{_datadir}/applications/%{desktop_id}.desktop
%{_datadir}/glib-2.0/schemas/%{desktop_id}.gschema.xml
%{_datadir}/icons/hicolor/scalable/apps/%{desktop_id}.svg
%{_datadir}/icons/hicolor/symbolic/apps/%{desktop_id}-symbolic.svg
%{_mandir}/man1/%{name}.1*
%{_metainfodir}/%{desktop_id}.metainfo.xml

%changelog
## START: Generated by rpmautospec
* Fri Jul 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 50.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_45_Mass_Rebuild

* Mon May 11 2026 David King <dking@redhat.com> - 50.0-1
- Update to 50.0 (#2454686)

* Sat Jan 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 49.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Sun Nov 02 2025 Simone Caronni <negativo17@gmail.com> - 49.1-1
- Update to 49.1, trim changelog

* Fri Oct 03 2025 Petr Schindler <pschindl@redhat.com> - 49.0.1-1
- Update to 49.0.1

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 48.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild
## END: Generated by rpmautospec
